name: 'Logic App Standard Infra'

on:
  workflow_dispatch:
  push:
    paths:
      - "bicep/**"
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
    - uses: actions/checkout@v3

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      id: infradeploy
      with:
        resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
        template: ./bicep/main.bicep
        deploymentmode: Incremental
        parameters: ./bicep/parameters/demo.json
        failOnStdErr: false