name: 'Logic App Standard'

on:
  workflow_dispatch:
  push:
    paths:
      - "workflows/**"
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
    - uses: actions/checkout@v3

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'

    - name: Package logic
      run: (cd workflows; mkdir -p ../output; zip -r ../output/logic.zip .)

    - name: Deploy to Logic App
      uses: Azure/functions-action@v1.3.1
      with:
        app-name: la-logicapp-standard-demo
        package: './output/logic.zip'
